### PR TITLE
Create 0000-template.md

### PR DESCRIPTION
**Pull request by sgillies**
This would be the template for an RFC I will write concerning Fiona 2.0. I floated the idea in https://fiona.groups.io/g/dev/message/1 and will make it more formal after this PR is merged.

Copied from https://github.com/Toblerity/Fiona/pull/739 (to be closed).

cc @geowurster @snorfalorpagus @rbuffat

### CODE REVIEW

**Review by hobu — APPROVED** [review]

**Comment by snowman2** [comment]
Per your note on the dev channel, I would be happy to be part of the team to review RFC's.

**Review by snowman2 — APPROVED** [review]
:+1:

**Comment by sgillies** [comment]
Last call for review @snorfalorpagus @rbuffat @geowurster !

**Review by geowurster — APPROVED** [review]

**Review by rbuffat — APPROVED** [review]

**Review by snorfalorpagus — APPROVED** [review]
Yes please 👍

**Pull request merged**
